export default {
  LOAD_BOOKING_ROOMS: "LOAD_BOOKING_ROOMS",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  USER_REGISTER: "USER_REGISTER",
  CREATE_RESERVATION: "CREATE_RESERVATION",
  LOAD_RESERVATION: "LOAD_RESERVATION",
  LOAD_RESERVATION_LIST: "LOAD_RESERVATION_LIST",
  UPDATE_RESERVATION: "UPDATE_RESERVATION",
};
